apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeaffinity-preferred
spec:
  affinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 80
      preference:
        matchExpressions:
        - key: mylabel/disk
          operator: In
          values:
          - ssd
  containers:
    - name: nginx
      image: nginx:latest