apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeaffinity-required
spec:
  affinity:
    requredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: mylabel/disk
          operator: In
          values:
          - ssd
          - hdd
  containers:
    - name: nginx
      image: nginx:latest