apiVersion: v1
kind: Pod
metadata:
  name: over-pod2
spec:
  containers:
  - name: nginx-request
    image: nginx:latest
    resources:
      limits:
        memory: "300Mi"
        cpu: "100m"
      requests:
        memory: "256Mi"
        cpu: "100m"