apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-hello-world
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: busybox
            args: ["sh", "-c", "date"]
            name: cronjob-ex