apiVersion: v1
kind: ServiceAccount
metadata:
  name:  9ilbert

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: kube-config-test-role

rules:
  - apiGroups: [""]         # 대상이 될 object의 API 그룹
    resources: ["services"] # 대상이 될 object의 이름
    verbs: ["get", "list"]  # 어떤 동작을 허용할 것인지 명시
  - apiGroups: [""]         # 대상이 될 object의 API 그룹
    resources: ["pods"] # 대상이 될 object의 이름
    verbs: ["get", "list"]  # 어떤 동작을 허용할 것인지 명시

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-config-test-rolebinding
  namespace: default

subjects:
- kind: ServiceAccount # 권한을 부여할 대상
  name: 9ilbert # 대상의 이름
  namespace: default

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role # Role에 정의된 권한 부여
  name: kube-config-test-role # 이 이름의 role을 subjects에 연결


---

# k8s v1.24 부터는 secret이 자동으로 생성되지 않음

apiVersion: v1
kind: Secret
metadata:
  name: 9ilbert-token
  annotations:
    kubernetes.io/service-account.name: 9ilbert
type: kubernetes.io/service-account-token