apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: node-reader

rules:
  - apiGroups: [""]         # 대상이 될 object의 API 그룹
    resources: ["nodes"] # 대상이 될 object의 이름
    verbs: ["get", "list"]  # 어떤 동작을 허용할 것인지 명시
