apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: service-reader

rules:
  - apiGroups: [""]         # 대상이 될 object의 API 그룹
    resources: ["services"] # 대상이 될 object의 이름
    verbs: ["get", "list"]  # 어떤 동작을 허용할 것인지 명시