apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-rolebinding
  namespace: default

subjects:
- kind: ServiceAccount # 권한을 부여할 대상
  name: alicek106 # 대상의 이름
  namespace: default

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role # Role에 정의된 권한 부여
  name: service-reader # 이 이름의 role을 subjects에 연결