apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-deployment-ns
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: my-hostname-pod
      labels:
        app: webserver
    spec:
      containers:
        - name: nginx
          image: alicek106/rr-test:echo-hostname
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name:  hostname-svc-ns
  namespace: production
spec:
  ports:
  - name: web-port
    port:  8080
    targetPort:  80
  selector:
    app: webserver
  type: NodePort