# secretGenerator: # secret 생성을 위한 지시문
# - name: kustomize-secret
#   type: kubernetes.io/tls # tls type
#   files:
#   - tls.crt=cert.crt # tls.crt 라는 키에 cert.crt 파일의 내용을 저장
#   - tls.key=cert.key

configMapGenerator:
- name: kustomize-secret
  files:
  - tls.crt=cert.crt # tls.crt 라는 키에 cert.crt 파일의 내용을 저장
  - tls.key=cert.key  