apiVersion: v1
kind: Pod
metadata:
  name: container-value-example
spec:
  containers:
  - name: my-container
    image: busybox
    args: ["tail", "-f", "/dev/null"]
    env:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: log-level-configmap
          key: LOG_LEVEL
    - name: k8s
      valueFrom:
        configMapKeyRef:
          name: start-k8s
          key: k8s