apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hpa-deploy
spec:
  selector:
    matchLabels:
      app: test
  replicas: 2
  template:
    metadata:
      name: nginx-hpa-pod
      labels:
        app: test
    spec:
      containers:
      - name: nginx-hpa-pod
        image: nginx
        resources:
          limits:
            cpu: "1000m"

---

kind: Service
apiVersion: v1
metadata:
  name:  nginx-hpa-svc
spec:
  selector:
    app:  test
  type:  ClusterIP
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  80


---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simple-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-hpa-deploy
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---

apiVersion: v1
kind: Pod
metadata:
  name: hpa-request-pod
spec:
  containers:
  - name: hpa-request-pod
    image: nginx:latest