apiVersion: v1
kind: Pod
metadata:
  name: init-container-usecase
spec:
  initContainers:
  - name: wait-other-service
    image: busybox
    command: ["sh", "-c", "until nslookup myservice; do echo wating..; sleep 1; done;"]
  containers:
  - name: nginx
    image: nginx:latest